In [68]:
import joblib

In [69]:
import numpy as np

In [70]:
# X_train = np.genfromtxt("Data/X_train_under.csv", delimiter=',')
# y_train = np.genfromtxt("Data/y_train_under.csv", delimiter=',')
X_train = np.genfromtxt("Data/X_train.csv", delimiter=',')
y_train = np.genfromtxt("Data/y_train.csv", delimiter=',')

In [71]:
X_train.shape

(11494, 146)

In [72]:
X_train

array([[ 0.68455576,  3.96026626,  0.62706628, ..., -0.22545945,
        -1.02519997, -0.69725532],
       [ 0.77366348,  0.25806456, -1.59472775, ..., -0.22545945,
         0.97541946, -0.69725532],
       [ 0.78986488,  0.17505555,  0.62706628, ..., -0.22545945,
         0.97541946, -0.69725532],
       ...,
       [-2.19119315,  0.35767537, -1.59472775, ..., -0.22545945,
        -1.02519997, -0.69725532],
       [ 0.74126067, -0.05736967,  0.62706628, ..., -0.22545945,
         0.97541946, -0.69725532],
       [ 0.47393753,  0.65650779,  0.62706628, ..., -0.22545945,
        -1.02519997, -0.69725532]])

In [73]:
y_train

array([0., 0., 0., ..., 0., 0., 0.])

# Batch Logistic Regression

In [74]:
from sklearn.linear_model import LogisticRegression

In [75]:
log_reg = LogisticRegression(max_iter=1000, random_state=42, class_weight="balanced")

In [76]:
log_reg.fit(X_train, y_train)

LogisticRegression(class_weight='balanced', max_iter=1000, random_state=42)

## Basic Evaluation

In [77]:
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix, precision_score, recall_score

### Train set

In [78]:
y_pred = log_reg.predict(X_train)

In [79]:
print(accuracy_score(y_train, y_pred))

0.772402992865843


In [80]:
print(confusion_matrix(y_train, y_pred))

[[6691 1908]
 [ 708 2187]]


In [81]:
print(precision_score(y_train, y_pred))

0.5340659340659341


In [82]:
print(recall_score(y_train, y_pred))

0.755440414507772


In [83]:
print(f1_score(y_train, y_pred))

0.6257510729613733


### Cross validation set

In [84]:
X_cv = np.genfromtxt("Data/X_cv.csv", delimiter=',')
y_cv = np.genfromtxt("Data/y_cv.csv", delimiter=',')

In [85]:
y_cv_pred = log_reg.predict(X_cv)

In [86]:
print(accuracy_score(y_cv, y_cv_pred))

0.7570459290187892


In [87]:
print(confusion_matrix(y_cv, y_cv_pred))

[[2254  648]
 [ 283  647]]


In [88]:
print(precision_score(y_cv, y_cv_pred))

0.4996138996138996


In [89]:
print(recall_score(y_cv, y_cv_pred))

0.6956989247311828


In [90]:
print(f1_score(y_cv, y_cv_pred))

0.5815730337078652


### Test set

In [91]:
X_test = np.genfromtxt("Data/X_test.csv", delimiter=',')
y_test = np.genfromtxt("Data/y_test.csv", delimiter=',')

In [92]:
y_test_pred = log_reg.predict(X_test)

In [93]:
print(accuracy_score(y_test, y_test_pred))

0.7612212943632568


In [94]:
print(confusion_matrix(y_test, y_test_pred))

[[2225  655]
 [ 260  692]]


In [95]:
print(precision_score(y_test, y_test_pred))

0.5137342242019303


In [96]:
print(recall_score(y_test, y_test_pred))

0.726890756302521


In [97]:
print(f1_score(y_test, y_test_pred))

0.6020008699434536


### Coefficients

In [98]:
np.argmax(np.abs(log_reg.coef_))

69

In [99]:
np.max(np.abs(log_reg.coef_))

0.4667013781241211

In [101]:
# joblib.dump(log_reg, "Models/default_log_reg_first_ver.pkl")
# joblib.dump(log_reg, "Models/log_reg_under_sample.pkl")
joblib.dump(log_reg, "Models/log_reg_no_under_sample_balanced_class_weight.pkl")

['Models/log_reg_no_under_sample_balanced_class_weight.pkl']