In [1]:
import joblib

In [2]:
import numpy as np

In [3]:
X_train = np.genfromtxt("Data/X_train.csv", delimiter=',')
y_train = np.genfromtxt("Data/y_train.csv", delimiter=',')

In [4]:
X_train

array([[-1.66129974, -0.42229418,  0.62190287, ..., -0.22697421,
        -1.02890375, -0.68855816],
       [ 0.74080339, -0.28876006,  0.62190287, ..., -0.22697421,
         0.97190821, -0.68855816],
       [-1.66129974,  1.16342347,  0.62190287, ..., -0.22697421,
        -1.02890375,  1.45231014],
       ...,
       [ 0.52169263, -0.13853418,  0.62190287, ..., -0.22697421,
        -1.02890375, -0.68855816],
       [-1.66129974, -0.82289653, -1.60796813, ..., -0.22697421,
        -1.02890375,  1.45231014],
       [ 0.30258187, -0.25537653,  0.62190287, ..., -0.22697421,
         0.97190821, -0.68855816]])

In [5]:
y_train

array([0., 0., 0., ..., 1., 0., 0.])

# Batch Logistic Regression

In [6]:
from sklearn.linear_model import LogisticRegression

In [7]:
log_reg = LogisticRegression(max_iter=1000, random_state=42)

In [8]:
log_reg.fit(X_train, y_train)

LogisticRegression(max_iter=1000, random_state=42)

In [9]:
y_pred = log_reg.predict(X_train)

In [10]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_train, y_pred))

[[9279  802]
 [2070 1259]]


In [11]:
joblib.dump(log_reg, "Models/default_log_reg_first_ver.pkl")

['Models/default_log_reg_first_ver.pkl']

# SGD Classifier

In [12]:
from sklearn.linear_model import SGDClassifier

In [13]:
sgd_clf = SGDClassifier()

In [14]:
sgd_clf.fit(X_train, y_train)

SGDClassifier()

In [15]:
joblib.dump(sgd_clf, "Models/sgd_clf.pkl")

['Models/sgd_clf.pkl']