In [58]:
import joblib

In [59]:
import numpy as np

In [60]:
X_train = np.genfromtxt("Data/X_train_under.csv", delimiter=',')
y_train = np.genfromtxt("Data/y_train_under.csv", delimiter=',')

In [61]:
X_train.shape

(5736, 149)

In [62]:
X_train

array([[ 0.74212583, -1.02108917,  0.62370107, ..., -0.23115431,
         0.96125128, -0.68064073],
       [ 0.55598673, -0.6381371 ,  0.62370107, ..., -0.23115431,
         0.96125128, -0.68064073],
       [ 0.89589291, -0.38838574,  0.62370107, ..., -0.23115431,
         0.96125128, -0.68064073],
       ...,
       [-2.2522858 ,  1.34322366,  0.62370107, ..., -0.23115431,
        -1.04031071,  1.46920388],
       [-2.18754177, -0.47163619, -1.60333219, ..., -0.23115431,
        -1.04031071,  1.46920388],
       [-0.42326681,  0.31091806, -1.60333219, ..., -0.23115431,
        -1.04031071,  1.46920388]])

In [63]:
y_train

array([0., 0., 0., ..., 1., 1., 1.])

# Batch Logistic Regression

In [64]:
from sklearn.linear_model import LogisticRegression

In [65]:
log_reg = LogisticRegression(max_iter=1000, random_state=42, class_weight="balance")

In [66]:
log_reg.fit(X_train, y_train)

LogisticRegression(class_weight='balance', max_iter=1000, random_state=42)

In [67]:
y_pred = log_reg.predict(X_train)

In [68]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_train, y_pred))

[[2228  640]
 [ 700 2168]]


In [69]:
# joblib.dump(log_reg, "Models/default_log_reg_first_ver.pkl")
joblib.dump(log_reg, "Models/log_reg_under_sample.pkl")

['Models/log_reg_under_sample.pkl']

In [70]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_train, y_pred))

0.7663877266387726


In [71]:
X_test = np.genfromtxt("Data/X_test.csv", delimiter=',')
y_test = np.genfromtxt("Data/y_test.csv", delimiter=',')

In [72]:
y_test_pred = log_reg.predict(X_test)

In [73]:
print(accuracy_score(y_test, y_test_pred))

0.7526096033402923


In [74]:
print(confusion_matrix(y_test, y_test_pred))

[[4390 1365]
 [ 531 1378]]


In [75]:
from sklearn.metrics import f1_score

In [76]:
print(f1_score(y_test, y_test_pred))

0.5924333619948409


In [77]:
np.argmax(np.abs(log_reg.coef_))

72

In [78]:
np.max(np.abs(log_reg.coef_))

0.40916056565451364