In [41]:
import joblib

In [42]:
import numpy as np

In [43]:
X_train = np.genfromtxt("Data/X_train.csv", delimiter=',')
y_train = np.genfromtxt("Data/y_train.csv", delimiter=',')

In [44]:
X_train.shape

(11494, 149)

In [45]:
X_train

array([[-1.65340347, -0.30513529,  0.62370107, ..., -0.23115431,
         0.96125128, -0.68064073],
       [ 0.89589291, -0.804638  , -1.60333219, ..., -0.23115431,
         0.96125128, -0.68064073],
       [ 0.4993357 , -0.05538393,  0.62370107, ..., -0.23115431,
         0.96125128, -0.68064073],
       ...,
       [ 0.74212583,  2.54203017,  0.62370107, ..., -0.23115431,
         0.96125128, -0.68064073],
       [ 0.74212583, -0.93783872,  0.62370107, ..., -0.23115431,
         0.96125128, -0.68064073],
       [ 0.74212583, -0.95448881,  0.62370107, ..., -0.23115431,
         0.96125128, -0.68064073]])

In [46]:
y_train

array([1., 0., 0., ..., 0., 0., 0.])

# Batch Logistic Regression

In [47]:
from sklearn.linear_model import LogisticRegression

In [48]:
log_reg = LogisticRegression(max_iter=1000, random_state=42, class_weight="balance")

In [49]:
log_reg.fit(X_train, y_train)

LogisticRegression(class_weight='balance', max_iter=1000, random_state=42)

In [50]:
y_pred = log_reg.predict(X_train)

In [51]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_train, y_pred))

[[7933  693]
 [1812 1056]]


In [52]:
joblib.dump(log_reg, "Models/default_log_reg_first_ver.pkl")

['Models/default_log_reg_first_ver.pkl']