In [1]:
import joblib

In [2]:
import numpy as np

In [3]:
X_train = np.genfromtxt("Data/X_train_under.csv", delimiter=',')
y_train = np.genfromtxt("Data/y_train_under.csv", delimiter=',')

In [4]:
X_train.shape

(5790, 146)

In [5]:
X_train

array([[-0.19842066,  1.03834922,  0.62706628, ..., -0.22545945,
         0.97541946, -0.69725532],
       [ 0.74126067, -0.70483992,  0.62706628, ..., -0.22545945,
         0.97541946, -0.69725532],
       [ 0.06080177, -0.98707054,  0.62706628, ..., -0.22545945,
        -1.02519997,  1.43419486],
       ...,
       [ 0.44963543, -0.65503452, -1.59472775, ..., -0.22545945,
        -1.02519997,  1.43419486],
       [ 0.74126067,  2.10086451,  0.62706628, ..., -0.22545945,
         0.97541946, -0.69725532],
       [-1.18670621, -0.73804352, -1.59472775, ..., -0.22545945,
        -1.02519997,  1.43419486]])

In [6]:
y_train

array([0., 0., 0., ..., 1., 1., 1.])

# Batch Logistic Regression

In [7]:
from sklearn.linear_model import LogisticRegression

In [8]:
log_reg = LogisticRegression(max_iter=1000, random_state=42, class_weight="balance")

In [9]:
log_reg.fit(X_train, y_train)

LogisticRegression(class_weight='balance', max_iter=1000, random_state=42)

In [10]:
y_pred = log_reg.predict(X_train)

In [11]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_train, y_pred))

[[2247  648]
 [ 694 2201]]


In [12]:
# joblib.dump(log_reg, "Models/default_log_reg_first_ver.pkl")
joblib.dump(log_reg, "Models/log_reg_under_sample.pkl")

['Models/log_reg_under_sample.pkl']

In [13]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_train, y_pred))

0.7682210708117444


In [14]:
X_test = np.genfromtxt("Data/X_test.csv", delimiter=',')
y_test = np.genfromtxt("Data/y_test.csv", delimiter=',')

In [15]:
y_test_pred = log_reg.predict(X_test)

In [16]:
print(accuracy_score(y_test, y_test_pred))

0.7515657620041754


In [17]:
print(confusion_matrix(y_test, y_test_pred))

[[2183  697]
 [ 255  697]]


In [18]:
from sklearn.metrics import f1_score

In [19]:
print(f1_score(y_test, y_test_pred))

0.5942028985507246


In [20]:
np.argmax(np.abs(log_reg.coef_))

69

In [21]:
np.max(np.abs(log_reg.coef_))

0.4462239066647565