In [1]:
import joblib

In [2]:
import numpy as np

In [3]:
# X_train = np.genfromtxt("Data/X_train_under.csv", delimiter=',')
# y_train = np.genfromtxt("Data/y_train_under.csv", delimiter=',')
X_train = np.genfromtxt("Data/X_train.csv", delimiter=',')
y_train = np.genfromtxt("Data/y_train.csv", delimiter=',')

In [4]:
X_train.shape

(11494, 146)

In [5]:
X_train

array([[ 0.68455576,  3.96026626,  0.62706628, ..., -0.22545945,
        -1.02519997, -0.69725532],
       [ 0.77366348,  0.25806456, -1.59472775, ..., -0.22545945,
         0.97541946, -0.69725532],
       [ 0.78986488,  0.17505555,  0.62706628, ..., -0.22545945,
         0.97541946, -0.69725532],
       ...,
       [-2.19119315,  0.35767537, -1.59472775, ..., -0.22545945,
        -1.02519997, -0.69725532],
       [ 0.74126067, -0.05736967,  0.62706628, ..., -0.22545945,
         0.97541946, -0.69725532],
       [ 0.47393753,  0.65650779,  0.62706628, ..., -0.22545945,
        -1.02519997, -0.69725532]])

In [6]:
y_train

array([0., 0., 0., ..., 0., 0., 0.])

# Batch Logistic Regression

In [7]:
from sklearn.linear_model import LogisticRegression

In [8]:
log_reg = LogisticRegression(max_iter=1000, random_state=42, class_weight="balanced")

In [9]:
log_reg.fit(X_train, y_train)

LogisticRegression(class_weight='balanced', max_iter=1000, random_state=42)

## Basic Evaluation

In [10]:
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix, precision_score, recall_score

### Train set

In [11]:
y_pred = log_reg.predict(X_train)

In [12]:
print(accuracy_score(y_train, y_pred))

0.772402992865843


In [13]:
print(confusion_matrix(y_train, y_pred))

[[6691 1908]
 [ 708 2187]]


In [14]:
print(precision_score(y_train, y_pred))

0.5340659340659341


In [15]:
print(recall_score(y_train, y_pred))

0.755440414507772


In [16]:
print(f1_score(y_train, y_pred))

0.6257510729613733


### Cross validation set

In [17]:
X_cv = np.genfromtxt("Data/X_cv.csv", delimiter=',')
y_cv = np.genfromtxt("Data/y_cv.csv", delimiter=',')

In [18]:
y_cv_pred = log_reg.predict(X_cv)

In [19]:
print(accuracy_score(y_cv, y_cv_pred))

0.7570459290187892


In [20]:
print(confusion_matrix(y_cv, y_cv_pred))

[[2254  648]
 [ 283  647]]


In [21]:
print(precision_score(y_cv, y_cv_pred))

0.4996138996138996


In [22]:
print(recall_score(y_cv, y_cv_pred))

0.6956989247311828


In [23]:
print(f1_score(y_cv, y_cv_pred))

0.5815730337078652


### Test set

In [24]:
X_test = np.genfromtxt("Data/X_test.csv", delimiter=',')
y_test = np.genfromtxt("Data/y_test.csv", delimiter=',')

In [25]:
y_test_pred = log_reg.predict(X_test)

In [26]:
print(accuracy_score(y_test, y_test_pred))

0.7612212943632568


In [27]:
print(confusion_matrix(y_test, y_test_pred))

[[2225  655]
 [ 260  692]]


In [28]:
print(precision_score(y_test, y_test_pred))

0.5137342242019303


In [29]:
print(recall_score(y_test, y_test_pred))

0.726890756302521


In [30]:
print(f1_score(y_test, y_test_pred))

0.6020008699434536


### Coefficients

In [31]:
np.argmax(np.abs(log_reg.coef_))

69

In [32]:
np.max(np.abs(log_reg.coef_))

0.4667013781241211

In [33]:
# joblib.dump(log_reg, "Models/default_log_reg_first_ver.pkl")
# joblib.dump(log_reg, "Models/log_reg_under_sample.pkl")
joblib.dump(log_reg, "Models/log_reg_no_under_sample_balanced_class_weight.pkl")

['Models/log_reg_no_under_sample_balanced_class_weight.pkl']