In [60]:
import pandas as pd

In [61]:
strat_train_set = pd.read_csv("Data/train.csv", index_col="enrollee_id")

In [62]:
strat_train_set.head()

Unnamed: 0      city  city_development_index gender  \
enrollee_id                                                        
20667              8253   city_21                   0.624    NaN   
4093              10067  city_103                   0.920   Male   
24146              1851   city_21                   0.624    NaN   
28323              4139   city_19                   0.682   Male   
16720              2473   city_21                   0.624   Male   

                 relevent_experience enrolled_university education_level  \
enrollee_id                                                                
20667        Has relevent experience       no_enrollment         Masters   
4093         Has relevent experience       no_enrollment        Graduate   
24146        Has relevent experience       no_enrollment        Graduate   
28323         No relevent experience    Full time course        Graduate   
16720         No relevent experience    Full time course     High School   

            major_discipline experience company_size         company_type  \
enrollee_id                                                                 
20667                   STEM          7          <10  Early Stage Startup   
4093                    STEM         19      100-500              Pvt Ltd   
24146                   STEM          5          NaN                  NaN   
28323                   STEM          2          NaN                  NaN   
16720                    NaN         10          NaN                  NaN   

            last_new_job  training_hours  target  
enrollee_id                                       
20667                  1              40     0.0  
4093                   2              48     0.0  
24146                  1             135     0.0  
28323              never              45     1.0  
16720              never              68     0.0

In [63]:
job_change = strat_train_set.drop("target", axis=1)
job_change_labels = strat_train_set["target"].copy()

In [64]:
job_change

Unnamed: 0      city  city_development_index gender  \
enrollee_id                                                        
20667              8253   city_21                   0.624    NaN   
4093              10067  city_103                   0.920   Male   
24146              1851   city_21                   0.624    NaN   
28323              4139   city_19                   0.682   Male   
16720              2473   city_21                   0.624   Male   
...                 ...       ...                     ...    ...   
5471              11284  city_103                   0.920    NaN   
4815              11964   city_57                   0.866   Male   
25935              5390   city_36                   0.893   Male   
6525                860   city_21                   0.624    NaN   
3366              15795   city_57                   0.866   Male   

                 relevent_experience enrolled_university education_level  \
enrollee_id                                                                
20667        Has relevent experience       no_enrollment         Masters   
4093         Has relevent experience       no_enrollment        Graduate   
24146        Has relevent experience       no_enrollment        Graduate   
28323         No relevent experience    Full time course        Graduate   
16720         No relevent experience    Full time course     High School   
...                              ...                 ...             ...   
5471          No relevent experience       no_enrollment        Graduate   
4815          No relevent experience    Full time course     High School   
25935        Has relevent experience       no_enrollment         Masters   
6525          No relevent experience    Full time course        Graduate   
3366         Has relevent experience       no_enrollment         Masters   

            major_discipline experience company_size         company_type  \
enrollee_id                                                                 
20667                   STEM          7          <10  Early Stage Startup   
4093                    STEM         19      100-500              Pvt Ltd   
24146                   STEM          5          NaN                  NaN   
28323                   STEM          2          NaN                  NaN   
16720                    NaN         10          NaN                  NaN   
...                      ...        ...          ...                  ...   
5471                    STEM        >20          NaN                  NaN   
4815                     NaN          4          NaN                  NaN   
25935                   STEM         10        10/49  Early Stage Startup   
6525                    STEM          5          NaN                  NaN   
3366                    STEM        >20      100-500              Pvt Ltd   

            last_new_job  training_hours  
enrollee_id                               
20667                  1              40  
4093                   2              48  
24146                  1             135  
28323              never              45  
16720              never              68  
...                  ...             ...  
5471                  >4              25  
4815               never             122  
25935                  2              57  
6525               never              16  
3366                  >4              50  

[13410 rows x 13 columns]

In [65]:
job_change.columns

Index(['Unnamed: 0', 'city', 'city_development_index', 'gender',
       'relevent_experience', 'enrolled_university', 'education_level',
       'major_discipline', 'experience', 'company_size', 'company_type',
       'last_new_job', 'training_hours'],
      dtype='object')

# Handle numerical attributes

In [66]:
num_attribs = ['city_development_index', 'training_hours']

In [67]:
job_change_num = job_change[num_attribs]

In [68]:
job_change_num

city_development_index  training_hours
enrollee_id                                        
20667                         0.624              40
4093                          0.920              48
24146                         0.624             135
28323                         0.682              45
16720                         0.624              68
...                             ...             ...
5471                          0.920              25
4815                          0.866             122
25935                         0.893              57
6525                          0.624              16
3366                          0.866              50

[13410 rows x 2 columns]

In [69]:
for attributes in job_change_num.columns:
    print(job_change_num[attributes].unique())

[0.624 0.92  0.682 0.887 0.91  0.913 0.939 0.897 0.556 0.926 0.899 0.794
 0.55  0.802 0.743 0.579 0.924 0.827 0.843 0.855 0.893 0.804 0.949 0.866
 0.74  0.555 0.89  0.689 0.739 0.836 0.754 0.698 0.925 0.691 0.776 0.884
 0.896 0.527 0.516 0.448 0.727 0.789 0.647 0.795 0.762 0.493 0.767 0.666
 0.923 0.722 0.856 0.64  0.487 0.563 0.865 0.512 0.775 0.788 0.763 0.738
 0.878 0.766 0.915 0.479 0.83  0.895 0.769 0.903 0.848 0.764 0.847 0.558
 0.725 0.78  0.742 0.898 0.745 0.68  0.796 0.645 0.735 0.84  0.921 0.807
 0.781 0.649 0.73  0.625 0.518 0.824 0.701 0.693 0.664]
[ 40  48 135  45  68  33   7 250  22 118  87  25  27  20  21  50  30  44
 158  28 120  23  11  42   4  24   2  78  80  52   3  90  43 114   9  62
  53  72  16  95  12  14  81   6 126 140  59 107 102  67 131  51  91 147
  36  56  17  18  54 194  38 100  60  10  83  69  47   8 130  57 108 152
  64 103 109 106  82 144  39  19  97 192  34 168  55 298  15  13 112  86
  41 105  85 136 278  61 146 182  37  31 166 111  46  94  49  26  29

In [70]:
import numpy as np

In [71]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(missing_values=np.nan, strategy="median")

In [72]:
imputer.fit(job_change_num)

SimpleImputer(strategy='median')

In [73]:
imputer.statistics_

array([ 0.903, 47.   ])

In [74]:
job_change_num = imputer.transform(job_change_num)

In [75]:
job_change_num

array([[  0.624,  40.   ],
       [  0.92 ,  48.   ],
       [  0.624, 135.   ],
       ...,
       [  0.893,  57.   ],
       [  0.624,  16.   ],
       [  0.866,  50.   ]])

In [76]:
from sklearn.preprocessing import StandardScaler

In [77]:
std_scaler = StandardScaler()

In [78]:
job_change_num = std_scaler.fit_transform(job_change_num)

In [79]:
job_change_num

array([[-1.66129974, -0.42229418],
       [ 0.74080339, -0.28876006],
       [-1.66129974,  1.16342347],
       ...,
       [ 0.52169263, -0.13853418],
       [-1.66129974, -0.82289653],
       [ 0.30258187, -0.25537653]])

# Handle Ordinal Categorical Attributes

In [80]:
ord_cat_attribs = ['relevent_experience', 'enrolled_university', 'education_level', 'experience', 'company_size', 'last_new_job']

In [81]:
job_change_ord_cat = job_change[ord_cat_attribs]

In [82]:
job_change_ord_cat

relevent_experience enrolled_university education_level  \
enrollee_id                                                                
20667        Has relevent experience       no_enrollment         Masters   
4093         Has relevent experience       no_enrollment        Graduate   
24146        Has relevent experience       no_enrollment        Graduate   
28323         No relevent experience    Full time course        Graduate   
16720         No relevent experience    Full time course     High School   
...                              ...                 ...             ...   
5471          No relevent experience       no_enrollment        Graduate   
4815          No relevent experience    Full time course     High School   
25935        Has relevent experience       no_enrollment         Masters   
6525          No relevent experience    Full time course        Graduate   
3366         Has relevent experience       no_enrollment         Masters   

            experience company_size last_new_job  
enrollee_id                                       
20667                7          <10            1  
4093                19      100-500            2  
24146                5          NaN            1  
28323                2          NaN        never  
16720               10          NaN        never  
...                ...          ...          ...  
5471               >20          NaN           >4  
4815                 4          NaN        never  
25935               10        10/49            2  
6525                 5          NaN        never  
3366               >20      100-500           >4  

[13410 rows x 6 columns]

In [83]:
for attributes in ord_cat_attribs:
    print(job_change_ord_cat[attributes].unique())

['Has relevent experience' 'No relevent experience']
['no_enrollment' 'Full time course' nan 'Part time course']
['Masters' 'Graduate' 'High School' nan 'Phd' 'Primary School']
['7' '19' '5' '2' '10' '4' '17' '15' '12' '8' '>20' '6' '13' '11' '16'
 '14' '20' '3' '1' '9' '18' '<1' nan]
['<10' '100-500' nan '50-99' '5000-9999' '10/49' '10000+' '1000-4999'
 '500-999']
['1' '2' 'never' '3' '>4' '4' nan]


In [84]:
ord_cat_imputer = SimpleImputer(missing_values=np.nan, strategy="most_frequent")

In [85]:
job_change_ord_cat_imputed = ord_cat_imputer.fit_transform(job_change_ord_cat)

In [86]:
job_change_ord_cat_imputed

array([['Has relevent experience', 'no_enrollment', 'Masters', '7',
        '<10', '1'],
       ['Has relevent experience', 'no_enrollment', 'Graduate', '19',
        '100-500', '2'],
       ['Has relevent experience', 'no_enrollment', 'Graduate', '5',
        '50-99', '1'],
       ...,
       ['Has relevent experience', 'no_enrollment', 'Masters', '10',
        '10/49', '2'],
       ['No relevent experience', 'Full time course', 'Graduate', '5',
        '50-99', 'never'],
       ['Has relevent experience', 'no_enrollment', 'Masters', '>20',
        '100-500', '>4']], dtype=object)

In [87]:
job_change_ord_cat_imputed = pd.DataFrame(job_change_ord_cat_imputed, columns=ord_cat_attribs)

In [88]:
def relevent_experience_to_numeric(experience):
  if experience == "Has relevent experience":
    return 1
  return 0

def enrolled_university_to_numeric(x):
  if x == 'no_enrollment':
    return 0
  if x == 'Part time course':
    return 1
  if x == 'Full time course':
    return 2

def education_level_to_numeric(x):
  if x == "Primary School":
    return 1
  if x == "High School":
    return 2
  if x == "Graduate":
    return 3
  if x == "Masters":
    return 4
  if x == "Phd":
    return 5

def experience_to_numeric(x):
    if x == '>20':
        return 21
    elif x == '<1':
        return 0
    else:
        return int(x)

def company_size_to_numeric(x):
    if x == '<10' :
        return 0
    if x == '10/49' :
        return 1
    if x == '50-99' :
        return 2
    if x == '100-500' :
        return 3
    if x == '500-999' :
        return 4
    if x == '1000-4999' :
        return 5
    if x == '5000-9999':
        return 6
    if x == '10000+':
        return 7

def last_new_job_to_numeric(x):
    if x == '>4' :
        return 5
    if x == 'never' :
        return 0
    else:
        return int(x)

In [89]:
job_change_ord_cat_imputed

relevent_experience enrolled_university education_level experience  \
0      Has relevent experience       no_enrollment         Masters          7   
1      Has relevent experience       no_enrollment        Graduate         19   
2      Has relevent experience       no_enrollment        Graduate          5   
3       No relevent experience    Full time course        Graduate          2   
4       No relevent experience    Full time course     High School         10   
...                        ...                 ...             ...        ...   
13405   No relevent experience       no_enrollment        Graduate        >20   
13406   No relevent experience    Full time course     High School          4   
13407  Has relevent experience       no_enrollment         Masters         10   
13408   No relevent experience    Full time course        Graduate          5   
13409  Has relevent experience       no_enrollment         Masters        >20   

      company_size last_new_job  
0              <10            1  
1          100-500            2  
2            50-99            1  
3            50-99        never  
4            50-99        never  
...            ...          ...  
13405        50-99           >4  
13406        50-99        never  
13407        10/49            2  
13408        50-99        never  
13409      100-500           >4  

[13410 rows x 6 columns]

In [90]:
job_change_ord_cat_encoded = job_change_ord_cat_imputed.copy() 

In [91]:
job_change_ord_cat_encoded['relevent_experience'] = job_change_ord_cat_imputed['relevent_experience'].apply(relevent_experience_to_numeric)
job_change_ord_cat_encoded['enrolled_university'] = job_change_ord_cat_imputed['enrolled_university'].apply(enrolled_university_to_numeric)
job_change_ord_cat_encoded['education_level'] = job_change_ord_cat_imputed['education_level'].apply(education_level_to_numeric)
job_change_ord_cat_encoded['experience'] = job_change_ord_cat_imputed['experience'].apply(experience_to_numeric)
job_change_ord_cat_encoded['company_size'] = job_change_ord_cat_imputed['company_size'].apply(company_size_to_numeric)
job_change_ord_cat_encoded['last_new_job'] = job_change_ord_cat_imputed['last_new_job'].apply(last_new_job_to_numeric)

In [92]:
job_change_ord_cat_encoded

relevent_experience  enrolled_university  education_level  experience  \
0                        1                    0                4           7   
1                        1                    0                3          19   
2                        1                    0                3           5   
3                        0                    2                3           2   
4                        0                    2                2          10   
...                    ...                  ...              ...         ...   
13405                    0                    0                3          21   
13406                    0                    2                2           4   
13407                    1                    0                4          10   
13408                    0                    2                3           5   
13409                    1                    0                4          21   

       company_size  last_new_job  
0                 0             1  
1                 3             2  
2                 2             1  
3                 2             0  
4                 2             0  
...             ...           ...  
13405             2             5  
13406             2             0  
13407             1             2  
13408             2             0  
13409             3             5  

[13410 rows x 6 columns]

In [93]:
job_change_ord_cat_encoded = job_change_ord_cat_encoded.to_numpy()

In [94]:
job_change_ord_cat_encoded

array([[ 1,  0,  4,  7,  0,  1],
       [ 1,  0,  3, 19,  3,  2],
       [ 1,  0,  3,  5,  2,  1],
       ...,
       [ 1,  0,  4, 10,  1,  2],
       [ 0,  2,  3,  5,  2,  0],
       [ 1,  0,  4, 21,  3,  5]], dtype=int64)

In [95]:
job_change_ord_cat_scaled = std_scaler.fit_transform(job_change_ord_cat_encoded)

In [96]:
job_change_ord_cat_scaled

array([[ 0.62190287, -0.56997915,  1.26429189, -0.46703132, -1.50308819,
        -0.58755418],
       [ 0.62190287, -0.56997915, -0.19463198,  1.29741157,  0.06803107,
         0.01381214],
       [ 0.62190287, -0.56997915, -0.19463198, -0.76110514, -0.45567535,
        -0.58755418],
       ...,
       [ 0.62190287, -0.56997915,  1.26429189, -0.0259206 , -0.97938177,
         0.01381214],
       [-1.60796813,  1.92460976, -0.19463198, -0.76110514, -0.45567535,
        -1.18892051],
       [ 0.62190287, -0.56997915,  1.26429189,  1.59148538,  0.06803107,
         1.81791111]])

# Handle Nominal Attributes

In [97]:
nom_cat_attribs = ['city', 'gender', 'major_discipline', 'company_type']

In [98]:
job_change_nom_cat = job_change[nom_cat_attribs]

In [99]:
nom_imputer = SimpleImputer(strategy="constant")

In [100]:
job_change_nom_cat_imputed = nom_imputer.fit_transform(job_change_nom_cat)

In [101]:
job_change_nom_cat_imputed_df = pd.DataFrame(job_change_nom_cat_imputed, columns=nom_cat_attribs)

In [102]:
job_change_nom_cat_imputed_df

city         gender major_discipline         company_type
0       city_21  missing_value             STEM  Early Stage Startup
1      city_103           Male             STEM              Pvt Ltd
2       city_21  missing_value             STEM        missing_value
3       city_19           Male             STEM        missing_value
4       city_21           Male    missing_value        missing_value
...         ...            ...              ...                  ...
13405  city_103  missing_value             STEM        missing_value
13406   city_57           Male    missing_value        missing_value
13407   city_36           Male             STEM  Early Stage Startup
13408   city_21  missing_value             STEM        missing_value
13409   city_57           Male             STEM              Pvt Ltd

[13410 rows x 4 columns]

In [103]:
for attributes in job_change_nom_cat_imputed_df.columns:
    print(job_change_nom_cat_imputed_df[attributes].unique())

['city_21' 'city_103' 'city_19' 'city_100' 'city_16' 'city_61' 'city_28'
 'city_136' 'city_155' 'city_114' 'city_23' 'city_105' 'city_11'
 'city_160' 'city_65' 'city_116' 'city_74' 'city_104' 'city_41' 'city_159'
 'city_67' 'city_36' 'city_102' 'city_98' 'city_57' 'city_143' 'city_75'
 'city_145' 'city_45' 'city_149' 'city_55' 'city_138' 'city_73' 'city_90'
 'city_97' 'city_91' 'city_40' 'city_71' 'city_30' 'city_50' 'city_128'
 'city_43' 'city_33' 'city_152' 'city_142' 'city_115' 'city_24' 'city_7'
 'city_26' 'city_72' 'city_46' 'city_48' 'city_162' 'city_64' 'city_83'
 'city_118' 'city_54' 'city_134' 'city_12' 'city_139' 'city_42' 'city_150'
 'city_78' 'city_93' 'city_9' 'city_179' 'city_59' 'city_76' 'city_2'
 'city_141' 'city_123' 'city_173' 'city_158' 'city_99' 'city_13'
 'city_126' 'city_77' 'city_10' 'city_53' 'city_70' 'city_157' 'city_84'
 'city_165' 'city_14' 'city_27' 'city_176' 'city_1' 'city_89' 'city_94'
 'city_69' 'city_101' 'city_44' 'city_37' 'city_80' 'city_120' 'city

In [104]:
from sklearn.preprocessing import OneHotEncoder

In [105]:
nom_cat_encoder = OneHotEncoder()

In [106]:
job_change_nom_cat_encoded = nom_cat_encoder.fit_transform(job_change_nom_cat_imputed_df)

In [107]:
job_change_nom_cat_encoded = job_change_nom_cat_encoded.toarray()

In [108]:
job_change_nom_cat_encoded

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 1., 0.]])

In [109]:
job_change_nom_cat_encoded.shape

(13410, 139)

In [110]:
nom_cat_encoder.categories_

[array(['city_1', 'city_10', 'city_100', 'city_101', 'city_102',
        'city_103', 'city_104', 'city_105', 'city_106', 'city_107',
        'city_109', 'city_11', 'city_114', 'city_115', 'city_116',
        'city_117', 'city_118', 'city_12', 'city_120', 'city_121',
        'city_123', 'city_126', 'city_127', 'city_128', 'city_129',
        'city_13', 'city_131', 'city_133', 'city_134', 'city_136',
        'city_138', 'city_139', 'city_14', 'city_141', 'city_142',
        'city_143', 'city_144', 'city_145', 'city_146', 'city_149',
        'city_150', 'city_152', 'city_155', 'city_157', 'city_158',
        'city_159', 'city_16', 'city_160', 'city_162', 'city_165',
        'city_166', 'city_167', 'city_171', 'city_173', 'city_175',
        'city_176', 'city_179', 'city_18', 'city_180', 'city_19', 'city_2',
        'city_20', 'city_21', 'city_23', 'city_24', 'city_25', 'city_26',
        'city_27', 'city_28', 'city_30', 'city_31', 'city_33', 'city_36',
        'city_37', 'city_39', 'city_

In [111]:
job_change_nom_cat_scaled = std_scaler.fit_transform(job_change_nom_cat_encoded)

In [112]:
job_change_nom_cat_scaled

array([[-0.03666178, -0.06704015, -0.11988396, ..., -0.22697421,
        -1.02890375, -0.68855816],
       [-0.03666178, -0.06704015, -0.11988396, ..., -0.22697421,
         0.97190821, -0.68855816],
       [-0.03666178, -0.06704015, -0.11988396, ..., -0.22697421,
        -1.02890375,  1.45231014],
       ...,
       [-0.03666178, -0.06704015, -0.11988396, ..., -0.22697421,
        -1.02890375, -0.68855816],
       [-0.03666178, -0.06704015, -0.11988396, ..., -0.22697421,
        -1.02890375,  1.45231014],
       [-0.03666178, -0.06704015, -0.11988396, ..., -0.22697421,
         0.97190821, -0.68855816]])

# Concatenate result

In [113]:
job_change_preprocessed = np.concatenate((job_change_num, job_change_ord_cat_scaled, job_change_nom_cat_scaled), axis=1)

In [114]:
job_change_preprocessed

array([[-1.66129974, -0.42229418,  0.62190287, ..., -0.22697421,
        -1.02890375, -0.68855816],
       [ 0.74080339, -0.28876006,  0.62190287, ..., -0.22697421,
         0.97190821, -0.68855816],
       [-1.66129974,  1.16342347,  0.62190287, ..., -0.22697421,
        -1.02890375,  1.45231014],
       ...,
       [ 0.52169263, -0.13853418,  0.62190287, ..., -0.22697421,
        -1.02890375, -0.68855816],
       [-1.66129974, -0.82289653, -1.60796813, ..., -0.22697421,
        -1.02890375,  1.45231014],
       [ 0.30258187, -0.25537653,  0.62190287, ..., -0.22697421,
         0.97190821, -0.68855816]])

In [115]:
job_change_preprocessed[0]

array([-1.66129974, -0.42229418,  0.62190287, -0.56997915,  1.26429189,
       -0.46703132, -1.50308819, -0.58755418, -0.03666178, -0.06704015,
       -0.11988396, -0.06055898, -0.12855025, -0.53521429, -0.12366795,
       -0.06590841, -0.02115721, -0.0172735 , -0.02115721, -0.11565315,
       -0.27908355, -0.05188246, -0.08219949, -0.02865234, -0.03562751,
       -0.02992751, -0.01931308, -0.0122133 , -0.0546971 , -0.03960368,
       -0.02591509, -0.07243878, -0.01495873, -0.04890794, -0.02443207,
       -0.02115721, -0.04491642, -0.18069462, -0.07891741, -0.01495873,
       -0.03346372, -0.03562751, -0.04966811, -0.04574235, -0.0376678 ,
       -0.05260008, -0.0172735 , -0.07698076, -0.05930577, -0.05115489,
       -0.02731792, -0.03346372, -0.0546971 , -0.07449087, -0.29580913,
       -0.21452702, -0.08401891, -0.06815343, -0.01495873, -0.02115721,
       -0.00863578, -0.08968444, -0.02285325, -0.03562751, -0.01495873,
       -0.00863578, -0.01931308, -0.08080879, -0.02115721, -0.03

In [116]:
job_change_preprocessed.shape

(13410, 147)

In [117]:
np.savetxt("Data/X_train.csv", job_change_preprocessed, delimiter=',')

In [118]:
np.savetxt("Data/y_train.csv", job_change_labels.to_numpy(), delimiter=',')